### ISSUE TITLE
[Physics][Gravity][Jumps] Wall jump

### ISSUE THREAD

**Issue by ThibaultHardin** [SojuJuseyo/Water-Drop-Project#25]
Comme son nom l'indique le wall jump va permettre au joueur d'utiliser les murs (ou juste des murs particuliers, a definir) pour re-sauter apres un premier saut.

La mechanique elle-meme semble evidente mais il faut prevoir dans le code des limitations a ce wall jump, meme si au final on est pas sur d'en avoir besoin.

Une option serait par exemple de pouvoir limiter le nombre de wall jump d'affilee. 
Une seconde serait de pouvoir diminuer la puissance du wall jump en fonction du nombre de jump fait par le joueur auparavant dans la meme lancee (c'est a dire que apres un wall jump si on resaute direct sur un mur ce saut sera mois puissant)

**STEPS:**

1. Utiliser un mur comme support pour sauter - Status: _Done_
2. Etre capable de limiter simplement dans le code le nombre maximum de sauts d'affilee - Status: _TO DO_
3. Etre capable de limiter simplement dans le code la puissance d'un wall jump de facon exponentielle en fonction du nombre de sauts d'affilee (si c'est comprehensible comme phrase) - Status: _TO DO_

**Comment by Weiko** [comment]
J'ai l'habitude de pouvoir sauter directement en appuyant sur espace quand je colle un mur et que je touche pas le sol, là faut aller dans la direction opposé en même temps c'est pas facile :((((
