### ISSUE TITLE
[Graphics]SceneManager

### ISSUE THREAD

**Issue by Weiko** [SojuJuseyo/Water-Drop-Project#35]
#35 
# Liste des taches : 
(ces taches seront exécutés dans l'ordre) 
@martin

- [x] **déroulement complet des scènes (en cours)**
- [ ] réalisation + intégration du loading screen et de l’écran de victoire
- [ ] réalisation + intégration de plusieurs maps 
- [ ] autoload de maps + load d'une map custom (optionnel)

**Comment by ThibaultHardin** [comment]
Missing :

Loading screen

**Comment by mfrancoisnantes** [comment]
Liste des taches : 

- [ ] déroulement complet des scènes (en cours)
- [ ] réalisation + intégration du loading screen et de l’écran de victoire
- [ ] réalisation + intégration de plusieurs maps 
- [ ] autoload de maps + load d'une map custom (optionnel)
