### ISSUE TITLE
[Audio][To Merge]Compression du son

### ISSUE THREAD

**Issue by Weiko** [SojuJuseyo/Water-Drop-Project#37]
Il faut trouver une lib de décodage à surcoucher. 
Le problème est qu'openAL ne permet de lire que des formats raw et donc des fichiers de son très lourds. Il faudrait pouvoir lire des fichiers plus petits (encodés/compressés) comme du ogg/mp3/wav/etc

**Comment by Sarevok117** [comment]
j'ai pu faire marcher fmod sur un projet solo, faut l’intégrer au projet now
